version: '3'

services:
  rqt:
    image: das:ros2-rqt
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - ".:/home/root/project"
    environment:
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 50
    profiles:
      - donotstart
  bag-record:
    image: das:ros2-base
    volumes:
      - "./tmp/bag/:/tmp/bag/"
    environment:
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 50
    profiles:
      - donotstart
  bag-play:
    image: das:ros2-base
    volumes:
      - "./tmp/bag/:/tmp/bag/"
    environment:
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 50
    profiles:
      - donotstart
    command:
      - "/bin/bash"
  ros2-base:
    image: das:ros2-base
    environment:
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 50
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - ".:/home/root/project"
    command:
      - "/bin/bash"
    profiles:
      - donotstart
