jobs:
  build-base-image:
    uses: .github/workflows/build-docker.yml@main
    with:
      path: docker/base-image
  build-application-image:
    uses: .github/workflows/build-docker.yml@main
    with:
      path: docker/built-application
  build-pixhawk-image:
    uses: .github/workflows/build-docker.yml@main
    with:
      path: docker/pixhawk
  build-rqt-image:
    uses: .github/workflows/build-docker.yml@main
    with:
      path: docker/rqt