on: [push]
jobs:
  build-base-image:
    uses: ./.github/workflows/build-docker.yml
    with:
      path: ./docker/base-image/Dockerfile
    secrets: inherit
  build-application-image:
    uses: ./.github/workflows/build-docker.yml
    with:
      path: ./docker/built-application/Dockerfile
    secrets: inherit
  build-pixhawk-image:
    uses: ./.github/workflows/build-docker.yml
    with:
      path: ./docker/pixhawk/Dockerfile
    secrets: inherit
  build-rqt-image:
    uses: ./.github/workflows/build-docker.yml
    with:
      path: ./docker/rqt/Dockerfile
    secrets: inherit
